---
kind: pipeline
type: kubernetes
name: Lint

trigger:
  event:
    - pull_request

steps:
  - name: lint
    image: node:20.6.1-slim
    commands:
      - npm i -g @antfu/ni
      - nci
      - nr lint
---
kind: pipeline
type: kubernetes
name: Staging deployment

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: docker-push
    image: plugins/docker
    settings:
      username:
        from_secret: NEXUS_DOCKER_USERNAME
      password:
        from_secret: NEXUS_DOCKER_PASSWORD
      repo: docker-private.averix.tech/pixeltranslate/app
      registry: docker-private.averix.tech
      dockerfile: ./Dockerfile
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
  - name: apply-kubernetes-file
    image: naorlivne/drone-kubernetes-apply
    depends_on: [docker-push]
    settings:
      kubernetes_token:
        from_secret: KUBERNETES_TOKEN
      kubernetes_api_host:
        from_secret: KUBERNETES_SERVER
      kubernetes_yaml_file: kubernetes/staging.yaml
      my_image_tag: ${DRONE_COMMIT_SHA}
