---
kind: pipeline
type: kubernetes
name: Lint

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
  - name: lint
    image: node:20.6.1-slim
    commands:
      - npm i -g @antfu/ni
      - nci
      - nr lint